### ISSUE TITLE
set directory permissions with bulk()

### ISSUE THREAD

**Issue by nfriedly** [archiverjs/node-archiver#140]
Hi, I have some code like this:

```js
  zip.bulk([
    { expand: true, cwd: sourceDir,  src: ['**', '**/.htaccess'], data: { mode: 0644 }  }
  ]);
```
And I've noticed that when creating a .zip, the `mode` is applied to files but not directories. (The directory permissions on the disk are 755, but the resulting .zip has 700.) 

I'm working on a mac, and I believe I've seen similar behavior on linux, so I'm not sure if this is related to the other open bugs or not. Either way, if there is a feature that lets me set directory permissions when doing a bulk operation that would be ideal, because I know what output permissions I want regardless of what they are on disk.

(I glanced at the new `.directory()` method, but I didn't see anything different there. And I'm guessing that it would drop the .htaccess file, so it probably wouldn't work for me anyway.)

Any thoughts? Should I just add a `directoryData` option and send a PR?

**Comment by ctalkington** [comment]
its true that bulk and directory really don't account for mode on directories. theres a few issues with the way mode is handled on directories (which is a newer addition to archiver) but those appear to mainly be on windows due to stat returning a 06xx mode.

ive been considering letting those data props also be functions that receive file data and return modified data as I really dont want to add another prop or argument.

also, if ever in question of what is really used internally, the best way is to switch to `json` format which will output all the files with whole stat object and file data.

the next version will most likely address mode issues once i finish the plugin overhaul.

**Comment by nfriedly** [comment]
Ok, that's cool. Letting `data` be a function would work for me. Want me to send a PR to do that?

**Comment by ctalkington** [comment]
have a peak at 6688585ec30b815d120b9d7f4a2e69ceb9e4098e

**Comment by nfriedly** [comment]
I left one comment on the commit, but that looks like it will work for me. Thanks for the quick turnaround!

**Comment by ctalkington** [comment]
im not sure theres much case for logging in that instance, as by default itd fail since `false` isnt a func, then data would need to be a function to even be used by the code. the || bit is just so that if someone doesnt return it doesn't break things.

id honestly opt for breaking before implementing logging for that case.

**Comment by ctalkington** [comment]
at the end of the day, using a function is an advanced use case, as such its going to normalize or verify what you give it. you're expected to know what your doing when using it.

**Comment by nfriedly** [comment]
Right, the issue isn't with the default `false`, it's if I as a user do something stupid like

```js
  zip.bulk([
    { expand: true, cwd: sourceDir,  src: ['**', '**/.htaccess'], data: function() { throw 'foo';}  }
  ]);
```
It will appear to work successfully because the `foo` error gets swallowed.

**Comment by ctalkington** [comment]
this should cover most cases without being too insane with checking.

c0f3b86845d395fd71f673ccaeb6e5994549b5e7

**Comment by ctalkington** [comment]
fyi if you need this right now, archiver@0.15.0 should now work as a semver match since 0.15.0-1 (alpha) is now published.

**Comment by nfriedly** [comment]
that works, thanks!

**Comment by ctalkington** [comment]
glad to hear, i usually don't publish for every change so alphas should still be mostly safe if not its good to hear about issues before final goes out.

**Comment by nfriedly** [comment]
Yep. BTW, in case anyone else wants it, this is the function I'm using:

```js
function setData(data) {
  data.stats || (data.stats = fs.statSync(path.join(sourceDir, data.name)));
  if (data.stats.isDirectory()) {
    data.mode = 0755; // octal
  } else {
    data.mode = 0644;
  }
  return data;
};
```

Doing a synchronous stat isn't ideal, but this code doesn't get run very often and (I think) it will at least ensure that the file doesn't get stat'd twice.

**Comment by ctalkington** [comment]
yah, that should work ok since theres logic to check and make if stats are already set in _append.

i think `bulk` is the only one that wouldn't have stats at that point. that is likely to become mute whenever `src(glob)` is implemented. `bulk` has always been a hack to allow for some more advanced cases.

**Comment by nfriedly** [comment]
Cool. Thanks again!

**Comment by ctalkington** [comment]
also, did you find out if the `directory` method works in your use case? I believe it should get .htaccess as its just reading dir and pulling everything.

**Comment by ctalkington** [comment]
the code for that should be:

```js
zip.directory(sourceDir, false, { mode: setData });
```

**Comment by nfriedly** [comment]
Yea, I just tried it out, and it looks like it does work. It also grabs the `.gitignore`, which the bulk method skipped, but that's not a big deal either way.

**Comment by ctalkington** [comment]
yah, this is where `src` will fill the void as itll support negative globs. ideally `bulk` will be removed a few versions out as its not the best for async usage either.

**Comment by arichiardi** [comment]
So I have a question on this as I have the same requirement as the OP, having to add dirs recursively and set the `mode` to 755 for them.

Can you confirm that this would not work recursively?

    zip.directory(sourceDir, {mode: 755})
