### ISSUE TITLE
Does archiver zip support read binary data from buffer ?

### ISSUE THREAD

**Issue by testtshoretel** [archiverjs/node-archiver#211]
@ctalkington  In my application, I get image from s3 and save it to a buffer. Then I use arhiver zip to zip this buffer to another buffer. But somehow the outcome is always unzippable. How do I handle this case?

Thanks,

   zip.on('error', function(err) {
        logger.debug('getGeneratePreviews zip err ' + err);
        .res.send(500);
        return;
    });
    
    this.zip.on('end', function() {
        logger.debug('getGeneratePreviews done');
        return;
    });

    var buf1 = Buffer.from(result.data);   //result.data is buffer data get from S3. 
     zip.append(buf1, {name: result.media_id.toString()});

**Comment by ctalkington** [comment]
are you calling `zip.finalize();`  to let it know you are done?

**Comment by testtshoretel** [comment]
@ctalkington  Yes. 

I added one more thing here: var buf1 = Buffer.from(result.data).t**oString('base64')**;  Still can not decode it.

**Comment by ctalkington** [comment]
Can I get a more complete example? the bits here are formatted poorly and don't reflect the whole usage

**Comment by testtshoretel** [comment]
@ctalkington Yes. 

Here is a simple flow: 

//req, res is http req and res
    zip = archiver('zip');
    zip.pipe(res);
 
    
    zip.on('error', function(err) {
        this.res.send(500);
        return;
    });
    
    zip.on('end', function() {
 
        return;
    });

//get image from s3
    s3.getObject( params, function(err, result) {
        if (err) {
            return;
        } else {
            var buf1 = Buffer.from(result.Body).toString('base64');
            zip.append(buf1, {name: result.media_id.toString()});
            zip.finalize();
        }

**Comment by ctalkington** [comment]
well buffers are supported so converting to string is NOT required. are you positive on the s3 giving back a buffer and the naming of such? does saving it to a file or outputting ad a string show as expected?

Usually when I've seen corruption in the past its due to not allowing enough time for everything to finish. With a file system that means listening to the end event of the writestream instead of archiver.

With http/express however, there is an example that correctly sets the headers for sending a zip attachment here:

https://github.com/archiverjs/node-archiver/blob/master/examples/express.js

I think this has made a difference in the past

**Comment by testtshoretel** [comment]
@ctalkington Thanks. I found the problem. I should use 'binary' for buffer. Thanks.
