### ISSUE TITLE
Creating a zip in the same folder as the files that need to be archived

### ISSUE THREAD

**Issue by astutesoftware** [archiverjs/node-archiver#319]
I have a folder d:\files\countries
d:\files\counrtries\20 has 2 files 1.csv and 2.csv

I need to make a zip called 20.zip which contains 1.csv and 2.csv in it and the zip needs to be created in d:\files\countries\20

What is happening is that it does zip the files correctly into the archive but it also includes itself in the archive.

In short how to exclude the manufactured zip file to be excluded from the archive itself since i am compressing files from the same folder and the target folder of the resultant zip is the same.

**Comment by ctalkington** [comment]
are you using the `directory` helper? you might try the `glob` helper which has the ability to pass the node-glob option `ignore`. archive is not aware of the underlying filename that it's being saved to. This is intentional so it functions with any type of stream. It's up to the user to handle the specifics of when it's going.
